### ISSUE TITLE
Action hanging when deploying function

### ISSUE THREAD

**Issue by Rocinante89** [Azure/actions-workflow-samples#15]
When using the functions action V1 to deploy to my production function on windows, the action hangs when spinning up the function. Logs here:

##[Initialize]
##[ValidateParameter]
##[ValidateAzureResource]
Using RBAC for authentication, GitHub Action will perform resource validation.
Sucessfully acquired site configs from function app!
Detected function app sku: Consumption
Sucessfully acquired app settings from function app (RBAC)!
Detected function app language: Dotnet
##[PreparePublishContent]
Will archive . into d:\a\_temp\temp_web_package_6845877634426281.zip as function app content
Will use api/zipdeploy to deploy (rbac authentication)
##[PublishContent]
Waiting for function app to spin up after app settings change.

I've let it run for in excess of five minutes with no sign of it deploying the zipped files.

**Comment by atbagga** [comment]
+1 
https://github.com/atbagga/SampleFunctionAppJava/runs/457627394?check_suite_focus=true

**Comment by Hazhzeng** [comment]
Hi @Rocinante89,
Thanks for reporting the issue, is this a Linux Consumption function app or a Windows Consumption function app?

For now, to mitigate the issue, you can set SCM_DO_BUILD_DURING_DEPLOYMENT = false and ENABLE_ORYX_BUILD = false in your app settings. This will prevent scm site from duplicating the build process.

**Comment by Rocinante89** [comment]
@Hazhzeng its a Windows Consumption Function app.

Thanks for responding. I’ll give those steps a shot.

**Comment by tpluscode** [comment]
Do I set those in `env` of my action yaml? I did that and [my build still hung](https://github.com/wikibus/sources.wikibus.org/runs/509433800?check_suite_focus=true)

**Comment by Hazhzeng** [comment]
Hi @tpluscode,

No, the app settings can be set in portal -> function app -> configuration -> application settings.

**Comment by tpluscode** [comment]
No luck. I set those app settings in portal and the build [hangs all the same](https://github.com/wikibus/sources.wikibus.org/runs/511897894) 😞

**Comment by DanielBMann9000** [comment]
I'm seeing the same behavior with a dedicated app service plan:
```

##[Initialize]
##[ValidateParameter]
##[ValidateAzureResource]
Using RBAC for authentication, GitHub Action will perform resource validation.
Sucessfully acquired site configs from function app!
Detected function app sku: Dedicated
Sucessfully acquired app settings from function app (RBAC)!
Detected function app language: Dotnet
##[PreparePublishContent]
Will archive functionbuild into /home/runner/work/_temp/temp_web_package_9327459972894883.zip as function app content
Will use api/zipdeploy to deploy (rbac authentication)
##[PublishContent]
Waiting for function app to spin up after app settings change.
##[error]The operation was canceled.
```

And for what it's worth, the word "successfully" is misspelled in the output.

**Comment by chris-gunawardena** [comment]
Same issue, setting SCM_DO_BUILD_DURING_DEPLOYMENT and ENABLE_ORYX_BUILD to false didn't help. Does anyone know a  workaround to deploy?

**Comment by chris-gunawardena** [comment]
Deleting the function and recreating it fixed it. (The flags were also set to false)

**Comment by Duchynko** [comment]
We're experiencing the same issue since yesterday, running Linux Function (Node) on the Consumption plan.

```
Run Azure/functions-action@v1
##[Initialize]
##[ValidateParameter]
##[ValidateAzureResource]
Using RBAC for authentication, GitHub Action will perform resource validation.
Sucessfully acquired site configs from function app!
Detected function app sku: Consumption
Sucessfully acquired app settings from function app (RBAC)!
Detected function app language: Node
##[PreparePublishContent]
Will archive . into /home/runner/work/_temp/temp_web_package_33096149634728955.zip as function app content
Will use WEBSITE_RUN_FROM_PACKAGE to deploy
##[PublishContent]
Waiting for function app to spin up after app settings change.
```

**Comment by tpluscode** [comment]
I recreated my app and the deployment succeeded the first time but then gets stuck on subsequent runs

**Comment by tpluscode** [comment]
FWIW I replaced the functions step with `Azure/webapps-deploy@v2` and I think it deploys without issues.

**Comment by g4c3** [comment]
I added the SCM_DO_BUILD_DURING_DEPLOYMENT = false and ENABLE_ORYX_BUILD = false in local.settings.json, restarted the app and all was good
