### ISSUE TITLE
Action for Deploying to Azure VM

### ISSUE THREAD

**Issue by shawndewet** [Azure/actions-workflow-samples#32]
I'm not finding an action yet for deploying an application to an Azure VM.  Am I missing it, or is this something that will still be added?

**Comment by raiyanalam** [comment]
Hi @shawndewet 
    We are actively working on actions that can be used to target Azure VMs. I would love to discuss more about your requirements and the solutions that we are working on. Please email me at moala [at] microsoft [dot] com so that we can take this further.

**Comment by raiyanalam** [comment]
Take a look at this github action: https://github.com/Azure/build-vm-image
It lets you bake applications into a VM image and then create VMs from this image.

**Comment by Chidilives** [comment]
@raiyanalam , It seems I can not find actions for deploying a .net core web application to an Azure VM (set) running in IIS. Only to Azure App services.
Is this not supported or am I looking at the wrong places?

**Comment by jpmadrigal07** [comment]
How to deploy nodejs to azure virtual machine
