### ISSUE TITLE
azure/login@v1 fails with self-hosted runner

### ISSUE THREAD

**Issue by edstancu** [Azure/actions-workflow-samples#72]
Hi,
I have just started using github actions with self-hosted runner and I am stucked at the azure login.
I get the following error message:

Run azure/login@v1
  with:
    creds:   ***
    enable-AzPSSession: true
    environment: azurecloud
    allow-no-subscriptions: false
C:\WINDOWS\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" cloud set -n azurecloud"
Done setting cloud: "azurecloud"
Error: Az CLI Login failed. Please check the credentials. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows
Error: Error: Error: The process 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd' failed with exit code 1

I have AZURE_CREDENTIALS as a secret with the following format:

  {
    "clientId": "xxxxx",
    "clientSecret": "xxxxx",
    "subscriptionId": "xxxxx",
    "tenantId": "xxxx"
  }

Do you have any suggestion what would be the reason? Is the secret badly formatted?
The service principal was created by our admin and I received the credentials from him, I can't create sp on the azure AD myself.

task in workflow file:
 - name: Login via Az module
        uses: azure/login@v1
        with: 
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true

**Comment by BALAGA-GAYATRI** [comment]
@edstancu  resourceManagerEndpointUrl should also be a part of the credentials in the secrets. Please check and confirm if this is how you are generating credentials https://github.com/Azure/login#configure-deployment-credentials

**Comment by edstancu** [comment]
@BALAGA-GAYATRI i don't generate the secret that way because I don't have permission to create a service principal. Our platform admin created it and I was provided the credentials. However, he is also not creating it directly, but requesting its creation from our Azure AD team. I will try with the ResourceManagerEndpointURL as well. Thanks,

**Comment by BALAGA-GAYATRI** [comment]
@edstancu any updates on this?

**Comment by edstancu** [comment]
Hi @BALAGA-GAYATRI yes, it works now, thank you very much.
